### ISSUE TITLE
There are two "Unknown" boards at the bottom of the list of Downloads

### ISSUE THREAD

**Issue by deshipu** [adafruit/circuitpython-org#464] opened 2020-04-23 08:03 UTC
If you scroll down the https://circuitpython.org/downloads page, you can see two "Unknown by Unknown" boards that link to https://circuitpython.org/board/unknown/ — I think this is an error.

**Comment by makermelissa** [comment] 2020-04-23 14:59
This is a duplicate of #463.

**Closed by makermelissa** 2020-04-23 14:59 UTC
